export const LawsuitTypes = {
  GETLAWSUIT_STARTED: 'lawsuit/GETLAWSUIT_STARTED',
  GETLAWSUIT_SUCCESS: 'lawsuit/GETLAWSUIT_SUCCESS',
  GETLAWSUIT_FAILURE: 'lawsuit/GETLAWSUIT_FAILURE',
  UPDATE_LAWSUITS_STARTED: 'lawsuit/UPDATE_LAWSUITS_STARTED',
  UPDATE_LAWSUITS_SUCCESS: 'lawsuit/UPDATE_LAWSUITS_SUCCESS',
  UPDATE_LAWSUITS_FAILURE: 'lawsuit/UPDATE_LAWSUITS_FAILURE',
};
export const AuthTypes = {
  LOGIN_STARTED: 'auth/LOGIN_STARTED',
  LOGIN_SUCCESS: 'auth/LOGIN__SUCCESS',
  LOGIN_FAILURE: 'auth/LOGIN_FAILURE',
  SIGNUP_STARTED: 'auth/SIGNUP_STARTED',
  SIGNUP_SUCCESS: 'auth/SIGNUP__SUCCESS',
  SIGNUP_FAILURE: 'auth/SIGNUP_FAILURE',
  UPDATE: 'auth/UPDATE',
  LOGOUT: 'auth/LOGOUT',
  CHANGE_REGISTERING: 'auth/CHANGE_REGISTERING',
};
export const LawyerTypes = {
  ADD_REQUEST: 'lawyer/ADD_REQUEST',
  ADD_SUCCESS: 'lawyer/ADD_REQUEST_SUCCESS',
  ADD_FAILURE: 'lawyer/ADD_FAILURE',
  REMOVE: 'lawyer/REMOVE',
};
export const ClientTypes = {
  GET_CLIENT_STARTED: 'client/GET_CLIENT_STARTED',
  GET_CLIENT_SUCCESS: 'client/GET_CLIENT_SUCCESS',
  GET_CLIENT_FAILURE: 'client/GET_CLIENT_FAILURE',
  LOAD_PROCESSES_STARTED: 'client/LOAD_PROCESSES_STARTED',
  LOAD_PROCESSES_SUCCESS: 'client/LOAD_PROCESSES_SUCCESS',
  LOAD_PROCESSES_FAILURE: 'client/LOAD_PROCESSES_FAILURE',
};
